displayName: |
  Demo endpoints
description: |
  Some demo endpoints to show how various features work, including this documentation.
/:
  get:
    description: |
      Get all the demos
    queryParameters:
    responses:
      200:
        body:
          application/json:
            example: |
              []
    securedBy: [none]

/{id}:
  get:
    description: |
      Get a single demo by id
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "name": "helloWorld4",
                "createdAt": "2016-11-30T04:06:37.000Z",
                "updatedAt": "2016-11-30T04:06:37.000Z"
              }
      404:
        body:
          plain/text:
            example: |
              Not Found
    securedBy: [none]

  put:
    description: |
      Update a single demo by id
    responses:
      200:
        body:
          plain/text:
            example: |
              OK
    securedBy: [none]

  delete:
    description: |
      Delete a single demo by id
    responses:
      200:
        body:
          plain/text:
            example: |
              OK
    securedBy: [none]
